services:
  nginx-proxy:
    image: nginx:1.29
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./includes:/home/andrew/web_server/includes:ro
      - ./nginx/certs/server.crt:/etc/nginx/ssl/server.crt:ro
      - ./nginx/certs/server.key:/etc/nginx/ssl/server.key:ro
    depends_on:
      - nginx-prod
    networks:
      - webnet
      - mitchellnet

  nginx-prod:
    image: nginx:1.29
    container_name: nginx-prod
    restart: unless-stopped
    volumes:
      - ./html/prod:/usr/share/nginx/html:ro
    networks:
      - webnet

networks:
  webnet:
    external: true
    name: web_server_webnet
  mitchellnet:
    external: true
