version: "3.9"

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy-dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - nginx-prod
    networks:
      - dev-webnet

  nginx-prod:
    image: nginx:latest
    container_name: nginx-prod-dev
    volumes:
      - ./html/prod:/usr/share/nginx/html:ro
    networks:
      - dev-webnet

networks:
  dev-webnet:
    name: dev-webnet
