services:
  nginx-proxy:
    image: nginx:1.29
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./includes:/home/andrew/web_server/includes:ro
      - /etc/ssl/certs/selfsigned.crt:/etc/nginx/ssl/selfsigned.crt:ro
      - /etc/ssl/private/selfsigned.key:/etc/nginx/ssl/selfsigned.key:ro
      - /etc/ssl/certs/selfsigned.crt:/etc/nginx/ssl/server.crt:ro
      - /etc/ssl/private/selfsigned.key:/etc/nginx/ssl/server.key:ro
    depends_on:
      - nginx-prod
      - nginx-test
    networks:
      - webnet

  nginx-prod:
    image: nginx:1.29
    container_name: nginx-prod
    restart: unless-stopped
    volumes:
      - ./html/prod:/usr/share/nginx/html:ro
    networks:
      - webnet

  nginx-test:
    image: nginx:1.29
    container_name: nginx-test
    restart: unless-stopped
    volumes:
      - ./html/test:/usr/share/nginx/html:ro
    networks:
      - webnet

networks:
  webnet:
    external: true
    name: web_server_webnet
